default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spree_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 }.to_i %>

test:
  <<: *default
  database: spree_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 }.to_i %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
